package com.pobaby.memorybox.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pobaby.memorybox.ui.mvp.model.other.ConfigurationModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONFIGURATION_MODEL".
*/
public class ConfigurationModelDao extends AbstractDao<ConfigurationModel, Long> {

    public static final String TABLENAME = "CONFIGURATION_MODEL";

    /**
     * Properties of entity ConfigurationModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SecurityType = new Property(1, int.class, "securityType", false, "SECURITY_TYPE");
        public final static Property PwdRuleType = new Property(2, int.class, "pwdRuleType", false, "PWD_RULE_TYPE");
        public final static Property GestrurePattern = new Property(3, String.class, "gestrurePattern", false, "GESTRURE_PATTERN");
    }


    public ConfigurationModelDao(DaoConfig config) {
        super(config);
    }
    
    public ConfigurationModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONFIGURATION_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SECURITY_TYPE\" INTEGER NOT NULL ," + // 1: securityType
                "\"PWD_RULE_TYPE\" INTEGER NOT NULL ," + // 2: pwdRuleType
                "\"GESTRURE_PATTERN\" TEXT);"); // 3: gestrurePattern
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONFIGURATION_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ConfigurationModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSecurityType());
        stmt.bindLong(3, entity.getPwdRuleType());
 
        String gestrurePattern = entity.getGestrurePattern();
        if (gestrurePattern != null) {
            stmt.bindString(4, gestrurePattern);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ConfigurationModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getSecurityType());
        stmt.bindLong(3, entity.getPwdRuleType());
 
        String gestrurePattern = entity.getGestrurePattern();
        if (gestrurePattern != null) {
            stmt.bindString(4, gestrurePattern);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ConfigurationModel readEntity(Cursor cursor, int offset) {
        ConfigurationModel entity = new ConfigurationModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // securityType
            cursor.getInt(offset + 2), // pwdRuleType
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // gestrurePattern
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ConfigurationModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSecurityType(cursor.getInt(offset + 1));
        entity.setPwdRuleType(cursor.getInt(offset + 2));
        entity.setGestrurePattern(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ConfigurationModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ConfigurationModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ConfigurationModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
