package com.pobaby.memorybox.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.pobaby.memorybox.ui.mvp.model.account.AccountModel;
import com.pobaby.memorybox.ui.mvp.model.account.AccountTypeModel;
import com.pobaby.memorybox.ui.mvp.model.other.ConfigurationModel;
import com.pobaby.memorybox.ui.mvp.model.other.SearchHistoryModel;

import com.pobaby.memorybox.db.AccountModelDao;
import com.pobaby.memorybox.db.AccountTypeModelDao;
import com.pobaby.memorybox.db.ConfigurationModelDao;
import com.pobaby.memorybox.db.SearchHistoryModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountModelDaoConfig;
    private final DaoConfig accountTypeModelDaoConfig;
    private final DaoConfig configurationModelDaoConfig;
    private final DaoConfig searchHistoryModelDaoConfig;

    private final AccountModelDao accountModelDao;
    private final AccountTypeModelDao accountTypeModelDao;
    private final ConfigurationModelDao configurationModelDao;
    private final SearchHistoryModelDao searchHistoryModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountModelDaoConfig = daoConfigMap.get(AccountModelDao.class).clone();
        accountModelDaoConfig.initIdentityScope(type);

        accountTypeModelDaoConfig = daoConfigMap.get(AccountTypeModelDao.class).clone();
        accountTypeModelDaoConfig.initIdentityScope(type);

        configurationModelDaoConfig = daoConfigMap.get(ConfigurationModelDao.class).clone();
        configurationModelDaoConfig.initIdentityScope(type);

        searchHistoryModelDaoConfig = daoConfigMap.get(SearchHistoryModelDao.class).clone();
        searchHistoryModelDaoConfig.initIdentityScope(type);

        accountModelDao = new AccountModelDao(accountModelDaoConfig, this);
        accountTypeModelDao = new AccountTypeModelDao(accountTypeModelDaoConfig, this);
        configurationModelDao = new ConfigurationModelDao(configurationModelDaoConfig, this);
        searchHistoryModelDao = new SearchHistoryModelDao(searchHistoryModelDaoConfig, this);

        registerDao(AccountModel.class, accountModelDao);
        registerDao(AccountTypeModel.class, accountTypeModelDao);
        registerDao(ConfigurationModel.class, configurationModelDao);
        registerDao(SearchHistoryModel.class, searchHistoryModelDao);
    }
    
    public void clear() {
        accountModelDaoConfig.clearIdentityScope();
        accountTypeModelDaoConfig.clearIdentityScope();
        configurationModelDaoConfig.clearIdentityScope();
        searchHistoryModelDaoConfig.clearIdentityScope();
    }

    public AccountModelDao getAccountModelDao() {
        return accountModelDao;
    }

    public AccountTypeModelDao getAccountTypeModelDao() {
        return accountTypeModelDao;
    }

    public ConfigurationModelDao getConfigurationModelDao() {
        return configurationModelDao;
    }

    public SearchHistoryModelDao getSearchHistoryModelDao() {
        return searchHistoryModelDao;
    }

}
