package com.pobaby.memorybox.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.pobaby.memorybox.ui.mvp.model.other.SearchHistoryModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SEARCH_HISTORY_MODEL".
*/
public class SearchHistoryModelDao extends AbstractDao<SearchHistoryModel, String> {

    public static final String TABLENAME = "SEARCH_HISTORY_MODEL";

    /**
     * Properties of entity SearchHistoryModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Type = new Property(1, int.class, "type", false, "TYPE");
        public final static Property KeyWord = new Property(2, String.class, "keyWord", false, "KEY_WORD");
    }


    public SearchHistoryModelDao(DaoConfig config) {
        super(config);
    }
    
    public SearchHistoryModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SEARCH_HISTORY_MODEL\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TYPE\" INTEGER NOT NULL ," + // 1: type
                "\"KEY_WORD\" TEXT);"); // 2: keyWord
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SEARCH_HISTORY_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SearchHistoryModel entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String keyWord = entity.getKeyWord();
        if (keyWord != null) {
            stmt.bindString(3, keyWord);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SearchHistoryModel entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getType());
 
        String keyWord = entity.getKeyWord();
        if (keyWord != null) {
            stmt.bindString(3, keyWord);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public SearchHistoryModel readEntity(Cursor cursor, int offset) {
        SearchHistoryModel entity = new SearchHistoryModel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getInt(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // keyWord
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SearchHistoryModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.getInt(offset + 1));
        entity.setKeyWord(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(SearchHistoryModel entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(SearchHistoryModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(SearchHistoryModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
